---

- name: Create user 
  user: uid={{ item.value.uid }} name={{ item.value.username }} createhome=yes home={{ item.value.homedir }} comment={{ item.value.fullname }} group={{ item.value.group }} state=present
  with_dict: "{{ user }}"

- name: Set password
  user: uid={{ item.value.uid }} name={{ item.value.username }} password={{ item.value.pwhash }} state=present
  with_dict: "{{ user }}"
  when: item.value.pwhash is defined

- name: Set member of group
  user: uid={{ item.value.uid }} name={{ item.value.username }} groups={{ item.value.groupof }} state=present
  with_dict: "{{ user }}"
  when: item.value.groupof is defined


- name: Set up authorized_keys for user
  authorized_key: user={{ item.value.username }} key={{ item.value.id_rsa_pub }}
  with_dict: "{{ user }}"
  when: item.value.id_rsa_pub is defined