---

- name: Local Groups
  include_tasks: groups.yml
  when: local_groups is defined

- name: Local Users
  include_tasks: users.yml
  when: local_users is defined

- name: Local Passwords
  include_tasks: passwords.yml
  when: local_passwords is defined

- name: Local Private Ssh Keys
  include_tasks: private-ssh-keys.yml
  when: local_ssh_keys is defined
